language: ruby
rvm:
  - 1.8.7
  - jruby-18mode

before_script: 
  - "sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev"
  - "rake ci:prepare_travis"
  - "psql -c 'create database chouette_test;' -U postgres"
script: "rake spec"
notifications:
  recipients:
    - luc.donnet@dryade.net
    - michel.etienne@dryade.net