language: ruby
rvm:
  - 1.8.7
  - jruby-18mode
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm:  1.8.7
      jdk: openjdk7
    - rvm:  1.9.3
      jdk: openjdk7
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev
before_script:
  - "bundle exec rake ci:db_travis_config"
  - "bundle exec rake db:create"
  - "bundle exec rake apartment:migrate"
script: "bundle exec rake spec"
