language: ruby
rvm:
  - 1.9.3
  - 2.1.3
  - jruby-1.7.16.1
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm:  1.9.3
    - jdk: openjdk7
    - rvm:  2.1.3
    - jdk: openjdk7        
notifications:
  email:        
    - mflorisson@cityway.fr
    - ldonnet@cityway.fr
    - metienne@cityway.fr
    - zbouziane@cityway.fr
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev
before_script:
  - "bundle exec rake ci:db_travis_config"
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
script: "bundle exec rake spec"
