language: ruby
rvm:
  - 1.8.7
  - jruby-18mode

before_script: 
  - "sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev"
  - "psql -c 'create database chouette_test;' -U postgres"
  - "rake ci:prepare_travis"
script: "rake spec"
matrix:
  include:
    - { rvm: jruby-18mode, env: JRUBY_OPTS="--1.8 --server -Xcext.enabled=false -Xcompile.invokedynamic=false" }
notifications:
  recipients:
    - luc.donnet@dryade.net