language: ruby
rvm:
  - 1.8.7
  - jruby-18mode
before_install:
  - sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev
before_script: 
  - "rake db:create"
  - "rake ci:prepare_travis"
script: "rake spec"
branches:
  only:
    - master
    - production