language: ruby
addons:
  postgresql: "9.3"
rvm:
  - 1.9.3
  - 2.1.5
  - 2.1.6
  - 2.2.2
  - jruby-1.7.19
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm:  1.9.3
      jdk: openjdk7
    - rvm:  2.1.5
      jdk: openjdk7
    - rvm:  2.1.6
      jdk: openjdk7
    - rvm:  2.2.2
      jdk: openjdk7      
notifications:
  email:
    - mflorisson@cityway.fr
    - ldonnet@cityway.fr
    - metienne@cityway.fr
    - zbouziane@cityway.fr
    - alban.peignier@af83.com
    - anicet.rohee@af83.com
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential ruby-dev libproj-dev libgeos-dev libffi-dev libsparsehash-dev zlib1g-dev libxslt1-dev libxml2-dev libbz2-dev
before_script:
  - "bundle exec rake ci:db_travis_config"
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
script: "bundle exec rake spec"
